### ISSUE TITLE
AppBar : add ability to assign color

### ISSUE THREAD

**Issue by Js-GitHub** [equinusocio/material-theme-appbar#13]
Please add ability to change color of the AppBar independent of the material_theme_accent_orange ( color ).

If AppBar color isn't specifically set use material accent color...

If AppBar color is set then use that color.

I'm using:

Neon.tmTheme
material_theme_accent_orange
Material-Theme-Darker.sublime-theme

**Comment by jonesj** [comment]
Thanks in advance...

Your contributions to ST3 are seriously and sincerely appreciated as I'm in front of the screen all day like so many others...

**Comment by equinusocio** [comment]
You mean move appbar color from material theme to appbar package? I can add specific appbar color settings.

**Comment by jonesj** [comment]
Exactly.  That would be perfect.  Thanks.  If possible, text color on AppBar should be configurable too...

With orange bar, white text was hard to see...

**Comment by equinusocio** [comment]
Yes. I can let use white or dark text through settings.

**Comment by Js-GitHub** [comment]
Thanks.  I'm still getting used to GitHub; however, want to say, you're truly a professional and appreciate everything you're doing to make life better and more enjoyable in the coding world for Sublime Text users.  There's one of you and thousands, if not millions of us, so someday I hope I'll be able to help and assist with some of the change requests, if that's permissible.

I noticed there's a help wanted label associated with this issue, does that mean anyone can make changes?  If so, I was wondering if it would be possible to make change using ColorSchemeEditor package.  Again, I'm new to GitHub and have never changed or created any schemes, but would sure like to learn.   If it's possible to make changes using ColorSchemeEditor package then I'll give it a try.

I'm attaching screen capture of how appbar looks which my current settings for reference.
![appbar](https://cloud.githubusercontent.com/assets/10727620/13173493/a98b1df6-d6b2-11e5-941f-6ec96a4bbd5b.PNG)

**Comment by equinusocio** [comment]
To edit the theme you have to use the compiler that i have built, ColorSchemeEditor is useless here. But don't worry :)

**Comment by Js-GitHub** [comment]
I'll have to learn more about node.js before I install it and use the compiler.

**Comment by ruidovisual** [comment]
So, how can we change the color of the appbar without affecting the accent color?

**Comment by equinusocio** [comment]
@Js-GitHub i'm working on this. I will separate the preferences so you'll have to set both material theme accent and abbpar color separately. I will fix the text color in another issue.

**Comment by Js-GitHub** [comment]
Thanks for adding changes.

I'm doing something wrong as I can't get the appbar to change colors based on the following:

"material_theme_accent_orange": true,
"material_theme_appbar_lime": true,
"material_theme_tree_headings": true,

I also uninstalled and reinstalled appbar package ( v1.0.4 )

I've restarted SublimeText.

appbar is still following "material_theme_accent_colors", not "material_theme_appbar_colors"

I'm going to continue searching for a solution.

I know it works because I've seen another user post where there were both orange and lime colored appbars...

**Comment by equinusocio** [comment]
The changes will be available from the next 1.1.0 release. Package control have some bug and doesn't check the new version. If you want now the last version you have to download the master branch

**Comment by Js-GitHub** [comment]
Thanks 
Are there any docs on how to edit these items using your compiler?  Could you point me to some links and/or tell me what I should read up on to use gulp and npm -i install  ( I assume this has to do with node.js ) that would help me be able to edit items affecting material_theme_appbar?

I would like to help and assist with edits in future at some point and be a contributor and not just a consumer.

Again, truly appreciate your patience and indulgence in assisting...   I know you've got tons of items on your plate and would truly love to assist someday...

**Comment by Js-GitHub** [comment]
Your instructions in the master branch for 1.1.0 were excellent.  I uninstalled 1.0.4 and downloaded and installed version 1.1.0 and I can now set appbar colors.  There are a couple of new items I've observed which I'll open under a new issue...

Thanks again.

Hope some day I can be of help and assistance... So any docs or links or info you can suggest to help me in that endeavor ( learn how to edit these themes using your compiler ) would be greatly appreciate.

Does editing either material-theme or appbar-theme require using your compiler?

And Color Schemes use " ColorSchemeEditor "?

**Comment by Js-GitHub** [comment]
Feel free to close this issue, thanks...

**Comment by equinusocio** [comment]
> Does editing either material-theme or appbar-theme require using your compiler?
Yes :)

> And Color Schemes use " ColorSchemeEditor "?
I don't use any software for the schemes, but if ColorSchemeEditor doesn't have bugs you can test it.

**Comment by basherdesigns** [comment]
Adding a dark color appbar background would be sweet too! or add a custom RGB color of our choice would also be most excellent :)
