### ISSUE TITLE
How to keep default theme color for top bar?

### ISSUE THREAD

**Issue by maeishoj** [equinusocio/material-theme-appbar#14]
I cannot seem to be able to keep the normal color for the top bar... anyone?

**Comment by equinusocio** [comment]
What do you mean with "normal color" if you don't use any of the accent colors the appbar will use the teal color. If you don't want the tinted appbar you have do disable/remove the addon package

**Comment by maeishoj** [comment]
the default color of the material theme. If I didn't add the theme appbar, then the top bar would have kept the default sublime text style. but else I can live with one of the colors or add my own :) Thanks for this anyway
