### ISSUE TITLE
Typo in README.md shouldn't it be "material_theme_appbar_indigio": true,

### ISSUE THREAD

**Issue by Js-GitHub** [equinusocio/material-theme-appbar#15]
Are following in README.md a typo?

"material_theme_appbar_lime: true"
"material_theme_appbar_orange: true"
"material_theme_appbar_purple: true"
"material_theme_appbar_red: true"
"material_theme_appbar_yellow: true"
"material_theme_appbar_indigo: true"

Shouldn't it be:
"material_theme_appbar_indigio": true,

**Comment by equinusocio** [comment]
No, it's indigo.
https://www.google.com/design/spec/style/color.html#color-color-palette

**Comment by Js-GitHub** [comment]
My apologies for not being clear.

What I meant to say is the placement of the double quotes in the README appear to be incorrect.  Instead of the double quotes " surrounding and encapsulating the whole string, shouldn't double quotes encapsulate and enclose the keyword only?.

Currently, double quotes enclose the whole string ( keyword and value ):
"material_theme_appbar_indigo: true"

Shouldn't double quotes only enclose the key?
"material_theme_appbar_indigo": true

Apologize for any confusion...
