### ISSUE TITLE
Shouldn't double quotes enclose key only? See  #15 

### ISSUE THREAD

**Issue by Js-GitHub** [equinusocio/material-theme-appbar#16]
Request [#15](https://github.com/equinusocio/material-theme-appbar/issues/15) be reopened...

My apologies for not being clear.

What I meant to say is the placement of the double quotes in the README appear to be incorrect. Instead of the double quotes " surrounding and encapsulating the whole string, shouldn't double quotes encapsulate and enclose the keyword only?.

Currently, double quotes enclose the whole string ( keyword and value ):
 "material_theme_appbar_indigo: true"

Shouldn't double quotes only enclose the key?
 "material_theme_appbar_indigo": true

Apologize for any confusion...

**Comment by PatinoBrian** [comment]
I'm getting an error parsing json file with `"material_theme_appbar_indigo: true"`. Please consider request #19.

**Comment by equinusocio** [comment]
Merged. Thanks!
