### ISSUE TITLE
"material_theme_accent_yellow" and "material_theme_appbar_yellow" look orange not yellow

### ISSUE THREAD

**Issue by Js-GitHub** [equinusocio/material-theme-appbar#17]
The colors for the following look more orange than yellow:

"material_theme_accent_yellow": true,
"material_theme_appbar_yellow": true,

The sidebar and appbar themes do not look same as yellow text in preferences, they look orange.  I suspect color values are different or possibly render different if color values are same.

![material-theme-yellow-looks-orange](https://cloud.githubusercontent.com/assets/10727620/13382324/92fc958a-de26-11e5-8d7f-0ea8cbb784d4.PNG)

**Comment by equinusocio** [comment]
Your appbar looks a bit weird. Make sure to restart Sublime Text. For the color I've use the 800 from material design yellow palette. This make a bit more contrast with the white labels. Orange accent (Deep Orange) is a lot darker. 

Maybe i will rename yellow to orange and orange to deep orange.

**Comment by Js-GitHub** [comment]
Thanks for exposing me to material design colors and palette.

I'd like to suggest & request Yellow #500 be used as it is "yellow" and when you add feature to allow light and dark ( white & black ) text on appbar, then dark ( black text ) will be very visible when appbar color is yellow or other bright colors.

See Yellow 500 below from material design below.  Yellow 500 looks good and black text is visible.

![yellow-500-pallette](https://cloud.githubusercontent.com/assets/10727620/13391540/dc5bb540-de89-11e5-938d-dba57aef7506.PNG)

**Comment by equinusocio** [comment]
The first yellow accent was 500. But there were many problems with the lighter theme. So i switched to the 800 one.

**Comment by Js-GitHub** [comment]
First I want to say I'm just glad and grateful to have access to your theme and have learned about sublime.

Ultimately it's your decision...

I just think, yellow should be yellow and if person  chooses light theme, then it's undestood they may have to selet dark accent.  There are plenty of dark accents to choose from.

Same goes for appbar...

If person choose white theme, then they should get upset if they couldn't also use white text.

For consistence, when selectin yellow should not get another color.

If it was originally 500, shouldn't it stay 500 and add additional accents or appbar colors if necessary.

Again, truly appreciate everything you have and are doing.  Whatever you decide I'm ok with it.

It's privileged to even have any themes...

**Comment by equinusocio** [comment]
At the moment i've no time to work on it. I will wait for a PR.

**Comment by Js-GitHub** [comment]
No problem.  There is no rush.
