### ISSUE TITLE
appbar color not uniform across whole bar is that to be expected or should it be one color?

### ISSUE THREAD

**Issue by Js-GitHub** [equinusocio/material-theme-appbar#18]
Curious,
Shouldn't the color on the app bar be uniform across the whole bar?

![appbar-teal-uniform](https://cloud.githubusercontent.com/assets/10727620/13382361/a11481cc-de27-11e5-92aa-ec0efac39eb8.PNG)

![appbar-lime-uniform](https://cloud.githubusercontent.com/assets/10727620/13382363/a80a62d0-de27-11e5-9ce9-5f8e5d1ac2b8.PNG)

It was uniform before 1.1.0:

![material-theme-orange](https://cloud.githubusercontent.com/assets/10727620/13382374/deeb2456-de27-11e5-879a-5af6bdee7532.PNG)

**Comment by equinusocio** [comment]
If You have ST build < 3106 you have to restart ST after theme/preferences changes
