### ISSUE TITLE
Appbar not displaying as expected

### ISSUE THREAD

**Issue by amucinom** [equinusocio/material-theme-appbar#2]
Hello!

The Appbar looks great on the screenshot! However, after installing the package, I get just a small glimpse of it at the very top left corner of the editor, as shown in this screenshot:
<img width="1440" alt="screen shot 2016-01-07 at 5 56 54 pm" src="https://cloud.githubusercontent.com/assets/4065569/12187363/7b29b23a-b568-11e5-97ca-765fd0d4c1d9.png">
Is there something I am doing wrong?
I installed through Package Control and I am not getting any error message on the console 

Thanks!

**Comment by bjankord** [comment]
Noticed the same thing after installing through Package control.

**Comment by amucinom** [comment]
I'm about to try and install it manually. Did you try it that way @bjankord ?

**Comment by adenvt** [comment]
Download the latest release, and extract in Sublime Package Dir... without rename it...

**Comment by baraamashaal** [comment]
+1 same thing here 
& thanks @amucinom it works

**Comment by Agent47DarkSoul** [comment]
Same issue, but now Material Theme stopped working completely.

**Comment by Droyk** [comment]
Same here owner fix this issue

**Comment by equinusocio** [comment]
Fixed. Please unistall old package and reinstall v1.0.2 (wait 30 mins) through Package Control. If you want to install it manually follow the same process, remove the folder and reinstall it from master branch.

**Comment by Droyk** [comment]
[**@equinusocio**](https://github.com/equinusocio) commented on [Jan 8, 2016, 3:54 PM GMT+5:30](https://github.com/equinusocio/material-theme-appbar/issues/2#issuecomment-169956272 "2016-01-08T10:24:35Z - Replied by Github Comment Enhancer"):
> Fixed. Please unistall old package and reinstall v1.0.2 (wait until delivered) through Package Control. If you want to install it manually follow the same process, remove the folder and then reinstall it from master branch.

Yup now it working thanxx [equinusocio](https://github.com/equinusocio) for fix this

**Comment by diego898** [comment]
Hmm. I just installed this and dont see anything showing up at all

**Comment by wzwizu** [comment]
Same for me, installed it, but nothing is showing up.

**Comment by equinusocio** [comment]
Just restart Sublime Text.

**Comment by wzwizu** [comment]
hehe restarting it multiple every day. Not showing at al.
