### ISSUE TITLE
Add : "material_theme_appbar_dark_text": true ( true = black , false = white )

### ISSUE THREAD

**Issue by Js-GitHub** [equinusocio/material-theme-appbar#20]
From [#17](https://github.com/equinusocio/material-theme-appbar/issues/17).

Please add following setting so text color on appbar can be either white or black.  This will allow text to be visible when appbar color is either very light ( use black text ) or dark ( use white text ).

"material_theme_appbar_dark_text": true // black text
"material_theme_appbar_dark_text": false // white text

![yellow-500-pallette](https://cloud.githubusercontent.com/assets/10727620/13391895/efd9a76a-de8b-11e5-978f-628e389be951.PNG)

![white-black-text-pallette](https://cloud.githubusercontent.com/assets/10727620/13391939/2e1d7682-de8c-11e5-9140-40433ec4dcd9.PNG)

![white-black-text-pallette2](https://cloud.githubusercontent.com/assets/10727620/13391976/63269746-de8c-11e5-96b8-05d63685c7c4.PNG)

![white-black-text-pallette3](https://cloud.githubusercontent.com/assets/10727620/13392053/d641694a-de8c-11e5-9bd7-3998d9693ba3.PNG)

**Comment by equinusocio** [comment]
`material_theme_appbar_dark_text ` isn't clear, it could referer to all the text. 
You should then make a preference for each interface area, like 'material_theme_appbar_tabs_dark_text'.. etc..

**Comment by Js-GitHub** [comment]
Originally I was thinking of all text in appbar as it is now.  All text is white right now.

To use your compiler do I have to know gulp and node.js, if so I'll start reading up on it.

**Comment by equinusocio** [comment]
You just have to install Node.js, `gulp-cli` globally, and then run `npm install`. Then run `gulp` inside the project folder. You have to make also a symlink to the repository and then put it inside ST packages folder.

**Comment by Js-GitHub** [comment]
Thanks so very much for details.  I will try that later.  Once I learn, maybe I can help or assist you implement some of the requests.  Of course with your permission...
