### ISSUE TITLE
Would it be possible to put the project name where it currently says 'PROJECT'?

### ISSUE THREAD

**Issue by BrockBeldham** [equinusocio/material-theme-appbar#21]
In the sidebar, there is a heading that says 'PROJECT' with a gear to it's left. It would be nice if the project I was in replaced this heading.
![screen shot 2016-03-01 at 9 36 53 am](https://cloud.githubusercontent.com/assets/7071735/13430047/5b1278c6-df91-11e5-8d0c-680bfd97da03.png)

It could be as simple as putting the name of the root folder your in as the 'Project Heading'

**Comment by equinusocio** [comment]
At the moment is a simple image. I can't without some python script, and i'm not a python developer.
