### ISSUE TITLE
material_theme_tree_headings not working

### ISSUE THREAD

**Issue by joezimjs** [equinusocio/material-theme-appbar#22]
`material_theme_tree_headings` Has no effect for me. The "Folders" title stays there regardless of the value I assign. I'm using Sublime build 3103 on Windows 7 Enterprise and Windows 7 Pro.

**Comment by custard-apple** [comment]
Same problem with me. I have added all the setting in Preferences->Setting-User but its showing  partial appbar as you can see in given image. 

![screenshot from 2016-03-23 14 57 38](https://cloud.githubusercontent.com/assets/13364661/13981039/a69a6dda-f107-11e5-8811-c6630b58c38e.png)

I'm using Sublime Text build 3103 on Ubuntu 12.04

**Comment by equinusocio** [comment]
@custard-apple please can you paste your preferences?

**Comment by custard-apple** [comment]
`{
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"font_face": "Roboto Mono",
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 17,
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"material_theme_accent_green": true,
	"material_theme_accent_indigo": true,
	"material_theme_accent_lime": true,
	"material_theme_accent_orange": true,
	"material_theme_accent_purple": true,
	"material_theme_accent_red": true,
	"material_theme_accent_yellow": true,
	"material_theme_appbar_indigo": true,
	"material_theme_appbar_lime": true,
	"material_theme_appbar_orange": true,
	"material_theme_appbar_purple": true,
	"material_theme_appbar_red": true,
	"material_theme_appbar_yellow": true,
	"material_theme_bold_tab": true,
	"material_theme_compact_sidebar": true,
	"material_theme_contrast_mode": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_tabs_autowidth": true,
	"material_theme_tabs_separator": true,
	"material_theme_tree_headings": true,
	"overlay_scroll_bars": "enabled",
	"theme": "Material-Theme.sublime-theme"
}
`

**Comment by equinusocio** [comment]
`material_theme_tree_headings` doesn't hides the app bar heading, but hides (when false) the sidebar HEADINGS like FOLDERS and OPENED FILES labels. TO remove the glitch try to remove appbar package.

**Comment by joezimjs** [comment]
![sublime-screenshot](https://cloud.githubusercontent.com/assets/1313898/14048426/2c2cc054-f27c-11e5-80cf-833cff5d79d2.png)

My Preferences are listed below:

```json
{
	"always_show_minimap_viewport": true,
	"auto_complete_commit_on_tab": true,
	"auto_complete_cycle": true,
	"bold_folder_labels": true,
	"caret_extra_bottom": 2,
	"caret_extra_width": 2,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"default_line_ending": "unix",
	"detect_slow_plugins": false,
	"drag_text": false,
	"draw_minimap_border": true,
	"enable_tab_scrolling": true,
	"fade_fold_buttons": false,
	"fallback_encoding": "UTF-8",
	"file_exclude_patterns":
	[
		".DS_Store"
	],
	"folder_exclude_patterns":
	[
		"tmp",
		".git",
		".svn",
		".hg",
		"CVS"
	],
	"font_face": "fira mono",
	"font_size": 11,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"match_brackets": true,
	"match_brackets_angle": true,
	"match_brackets_braces": true,
	"match_brackets_content": true,
	"match_brackets_square": true,
	"material_theme_accent_lime": true,
	"material_theme_bold_tab": true,
	"material_theme_contrast_mode": true,
	"material_theme_disable_folder_animation": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"material_theme_tabs_separator": true,
	"material_theme_tree_headings": false,
	"open_files_in_new_window": false,
	"overlay_scroll_bars": "enabled",
	"rulers":
	[
		80,
		100
	],
	"scroll_past_end": true,
	"shift_tab_unindent": true,
	"show_encoding": true,
	"show_line_endings": true,
	"spell_check": false,
	"tab_size": 4,
	"theme": "Material-Theme.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"typescript_plugin_tsc_version": "1.6.2",
	"word_wrap": false
}
```

**Comment by equinusocio** [comment]
I have no problem using your preferences. See the screen. 
<img width="784" alt="screen shot 2016-03-29 at 09 29 14" src="https://cloud.githubusercontent.com/assets/10454741/14100844/bc217d96-f590-11e5-9df9-dcbf7de2183e.png">

Try my preferences:
```json
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"caret_extra_bottom": 0,
	"caret_extra_top": 0,
	"caret_extra_width": 1,
	"caret_style": "phase",
	"close_windows_when_empty": false,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"draw_white_space": "all",
	"enable_tab_scrolling": false,
	"fade_fold_buttons": true,
	"folder_exclude_patterns":
	[
		".svn",
		".git",
		".hg",
		"CVS",
		"node_modules"
	],
	"font_face": "Fira Code",
	"font_size": 13,
	"highlight_line": true,
	"ignored_packages":
	[
		"Autoprefixer",
		"Gutter Color",
		"Material Theme - White Panels",
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_accent_indigo": true,
	"material_theme_appbar_indigo": true,
	"material_theme_compact_panel": true,
	"material_theme_panel_separator": true,
	"material_theme_tree_headings": false,
	"overlay_scroll_bars": "enabled",
	"preview_on_click": false,
	"tab_size": 2,
	"theme": "Material-Theme-Darker.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"use_tab_stops": true,
	"word_wrap": false
}
```

**Comment by custard-apple** [comment]
I used your preferences still i don't get appbar. You can see snapshot below.

![appbar](https://cloud.githubusercontent.com/assets/13364661/14132504/329f1022-f664-11e5-93be-629f3a7f9125.png)

**Comment by custard-apple** [comment]
Hey Thanks it works...

**Comment by joezimjs** [comment]
@equinusocio 
I've uninstalled Material Theme and the appbar, reinstalled them and still see "Folders".  Also tried your preferences before and after the re-installs.

Take a look at the screenshot below. I was editing items within the highlighted area and was having an effect on the "FOLDERS" heading. I assume the last number in the `color` array is supposed to be opacity, right? For whatever reason, no matter what I set it to, it has no effect. Are there any other ways to adjust the opacity of that header? Is there a documentation resource I can look at that gives you information on what all the properties are?

![sublime-sidebar](https://cloud.githubusercontent.com/assets/1313898/14142832/a7625dd6-f64d-11e5-8629-a731731269dc.png)

**Comment by custard-apple** [comment]
Check if you have make these true.If so make it false
  "material_theme_disable_fileicons"        : false , // Hide siderbar file
type icons
  "material_theme_disable_folder_animation" : false , // Disable folder
animation

**Comment by joezimjs** [comment]
@custard-apple No change. Thanks for trying though.

**Comment by custard-apple** [comment]
Try to uninstall all other themes in your sublime instead of MT & MT-appbar...

**Comment by joezimjs** [comment]
@custard-apple I have no other themes installed

**Comment by joezimjs** [comment]
@custard-apple @equinusocio I've disables ALL plugins except for Package Manager, Material Theme, and Material Theme Appbar. Not seeing any difference.

**Comment by equinusocio** [comment]
Maybe you have to remove, not disable other themes..

**Comment by joezimjs** [comment]
I disabled all _plugins_ and had deleted all other themes before.

**Comment by ScottKaye** [comment]
I'm having the same issue, tried reinstalling everything, toggling every config value, and no dice.

![image](https://cloud.githubusercontent.com/assets/2024318/14195378/a04af6c2-f786-11e5-9521-9c319f80f60c.png)

Toggling `material_theme_tree_headings` has no effect for me either.  Here's my entire user prefs:

```json
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"caret_extra_bottom": 1,
	"caret_extra_top": 1,
	"caret_extra_width": 1,
	"caret_style": "phase",
	"color_scheme": "Packages/User/SublimeLinter/Oceanic Next (SL).tmTheme",
	"drag_text": false,
	"draw_minimap_border": true,
	"font_face": "Consolas",
	"font_options":
	[
		"subpixel_antialias",
		"directwrite"
	],
	"font_size": 13,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_accent_indigo": true,
	"material_theme_bold_tab": true,
	"material_theme_compact_sidebar": false,
	"material_theme_disable_tree_indicator": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": false,
	"material_theme_tree_headings": false,
	"overlay_scroll_bars": "enabled",
	"theme": "Material Seti.sublime-theme"
}
```

The only package I have installed that messes with the sidebar is SideBarEnhancements, which I have uninstalled (and reinstalled) to no effect.

**Comment by joezimjs** [comment]
I even tried re-installing Sublime, though I didn't delete all the packages and user data that got left behind.

**Comment by equinusocio** [comment]
@joezimjs You think we can close this issue?

**Comment by joezimjs** [comment]
@equinusocio Might as well. I don't think it's your fault. I haven't been able to find anything on the internet about it because apparently there's very very little documentation regarding these themes. I always find things about color schemes instead. Do you have a good place for looking at documentation about these themes, @equinusocio ?

**Comment by equinusocio** [comment]
@joezimjs i found only this
http://docs.sublimetext.info/en/latest/

**Comment by ScottKaye** [comment]
For what it may be worth, I recently synced my package control settings with Sublime running on my laptop, after completely nuking my Packages/User folder.  The `"material_theme_tree_headings": false,` actually took effect somehow, despite having the exact same configuration on my desktop.

Running build 3103 on identical Windows 10 versions.

**Comment by joezimjs** [comment]
@equinusocio I'm not sure how that's helpful since they specifically don't cover themes: http://docs.sublimetext.info/en/latest/customization/customization.html?highlight=theme

@ScottKaye I've thought about it, but I don't think it's worth the effort to hide the word "Folders"... I'll keep it in mind though. I get the same thing on both of my Windows 7 machines, so I'm curious what is so unique about them.
