### ISSUE TITLE
charcoal theme

### ISSUE THREAD

**Issue by enkia** [equinusocio/material-theme-appbar#23]
Any interest in implementing a Charcoal theme? The existing options are great but a bit too bright for me using the Darker theme. I [forked](https://github.com/enkia/material-theme-appbar) and added it for my own use so I thought I'd ask just in case.

Options available:
```json
material_theme_appbar_charocal":        true, // default teal highlights and needed for other colors
material_theme_appbar_charocal_lime":   true,
material_theme_appbar_charocal_purple": true,
material_theme_appbar_charocal_red":    true,
material_theme_appbar_charocal_orange": true,
material_theme_appbar_charocal_yellow": true,
material_theme_appbar_charocal_indigo": true,

```

**Comment by equinusocio** [comment]
What do you mean? can you post a screenshot?

**Comment by enkia** [comment]
![tet](https://cloud.githubusercontent.com/assets/255730/13719019/15d2862c-e7be-11e5-9ddb-cb21797fe8ca.png)


Offers up a bit of contrast to those who use groups and panes but still want a dark background, overall. I used your red scheme here but all your other color app bar schemes are available as well in 'charcoal'.

**Comment by theiviaxx** [comment]
I agree, or at the very least add a grey option to the list

**Comment by incace** [comment]
Yes please implement...

**Comment by victorjeman** [comment]
+1

**Comment by equinusocio** [comment]
I can made a charcoal appbar but with a fixed white accent color, as for the other colors.

**Comment by incace** [comment]
I was thinking something along these lines...

**Light**
![st3-matappbar-lite](https://cloud.githubusercontent.com/assets/61343/15808570/a083358e-2b37-11e6-9285-56d4a8427a47.jpg)

**Dark**
![st3-matappbar-dark](https://cloud.githubusercontent.com/assets/61343/15808572/ba7712d0-2b37-11e6-86ae-f8d19d71c909.jpg)

Bueno?

**Comment by theiviaxx** [comment]
@equinusocio Thank you!

**Comment by adrianoresende** [comment]
I uninstalled because it does not have color line in tab =(

**Comment by equinusocio** [comment]
👍🏻
