### ISSUE TITLE
App Bar color doesn't match accent color

### ISSUE THREAD

**Issue by amucinom** [equinusocio/material-theme-appbar#24]
Hello!

I've just noticed that when changing the accent color, the app bar doesn't change with it. For example, changing the accent color to indigo will change the colors of the open folders and stuff on the sidebar, but the Appbar will remain teal, doesn't matter what accent you switch to.

Here is a screenshot:
<img width="1552" alt="screen shot 2016-03-20 at 8 03 18 pm" src="https://cloud.githubusercontent.com/assets/4065569/13909842/11e1bc98-eed7-11e5-93c4-580bab9e206f.png">

**Comment by equinusocio** [comment]
Did you read the readme files? To change the appbar accent you have to set a separate preference.
