### ISSUE TITLE
No updates to tabbar, sidebar despite installed package via package control

### ISSUE THREAD

**Issue by va01** [equinusocio/material-theme-appbar#25]
I uninstalled and reinstalled the App Bar via package control and, unfortunately, the App Bar no longer appears to be activating. I have tried several times and have restarted Sublime Text 3.

Any help would be appreciated! 

Thank you.

**Comment by va01** [comment]
The following sequence worked for me but it may not for you:

1. Uninstall App Bar
2. Uninstall Material Theme
3. Delete all related settings in User-Settings (see the menu bar option)
4. Reinstall Material Theme
5. Reinstall App Bar.

**Comment by OJ7** [comment]
Tried that and unfortunately still not working for me. Thanks for the reply!

**Comment by bjones6** [comment]
The sequence did not work for me either.

**Comment by bjones6** [comment]
Figured out the solution. Follow steps 1-5 from @va01 and then manually add 

````json
    "theme": "Material-Theme.sublime-theme",
    "color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
````

To Settings - User. On OSX you can find that file by going to Sublime Text > preferences > Settings - User .
