### ISSUE TITLE
Can you please provide the artwork (psd or ai or whatever) to create new themes?

### ISSUE THREAD

**Issue by cavneb** [equinusocio/material-theme-appbar#26]
I would like to submit PR's with new color themes, but I would prefer not to re-create the artwork. Do you have the files available?

**Comment by equinusocio** [comment]
What color themes?

**Comment by cavneb** [comment]
I mean the files that are in each of the folders here: https://github.com/equinusocio/material-theme-appbar/tree/master/assets ... I assume you have the files saved as PSD or something right?

**Comment by equinusocio** [comment]
ok, you mean accent color. There is only one image here (the source is a sketch file). The others colors are defined by code. :+1:
