### ISSUE TITLE
The theme appbar makes tab switching laggy

### ISSUE THREAD

**Issue by pingshunhuangalex** [equinusocio/material-theme-appbar#28]
When I use the appbar, I noticed that when I switch the tab by clicking, the cursor "click" action will get stuck for a tiny little while, it makes the experience laggy.

A worse thing is sometimes when I move my cursor quickly after switching tabs, it'll drag the tab out to form a new window, or sometimes selecting some code in the window. Is there a way to fix it? Thanks.

I'm using a laptop, but the hardware isn't very bad.
CPU: Intel Core i7-4702MQ
RAM: 16G
OS: Win10 64-bit
Sublime: latest (3103)

**Comment by equinusocio** [comment]
@pingshunhuangalex On any of my computers I get this problem. Are you sure that it's caused by this package and not by other packages?

**Comment by pingshunhuangalex** [comment]
Well, I'm not sure if my test is scientific or not, but if I disable the app bar and turn on tab separator for material theme, it's quite smooth. So I assume it must be come from the app bar and the animation itself. Thanks.

**Comment by pingshunhuangalex** [comment]
Hi equinusocio

I found the problem finally, I think it's the gitgutter I used that's slowing things down. As long as I disable that, the problem is gone.

Having said that, I really need gitgutter though. Is there a way to make 2 of you guys get along better as gitgutter is also a quite popular plugin. Thanks.

**Comment by equinusocio** [comment]
I also use gitgutter with no problems! I really don't know how help you :(

**Comment by pingshunhuangalex** [comment]
Ok, no problems then. Maybe just my computer is not powerful enough.

**Comment by equinusocio** [comment]
I don't think. I think there is a problem in your ST. Maybe some corrupted data or old plugin. May you can try to delete all data folder and start with a new fresh ST.
