### ISSUE TITLE
Unable to decode dirty_icon.png

### ISSUE THREAD

**Issue by buildersbrewery** [equinusocio/material-theme-appbar#29]
```text
Unable to decode Packages/Material Theme - Appbar/assets/commons/dirty_icon.png
```

from Sublime Text console after startup.

* Material Theme - Appbar: `v1.2.0`
* Material Theme: `v2.1.1`
* Sublime Text `Build 3111 dev`
* Win10 x64 Pro

**Comment by equinusocio** [comment]
Try to completely remove and reinstall the theme and the appbar addon

**Comment by buildersbrewery** [comment]
no change

**Comment by asifm42** [comment]
Getting the same error. Tried removing and reinstalling theme and appbar addon with no luck.

- Material Theme - Appbar: v1.2.0
- Material Theme: v2.1.5
- Sublime Text Build 3103 stable
- OS X El Capitan v 10.11.4

**Comment by buildersbrewery** [comment]
thanks

/cc @saadq FYI
