### ISSUE TITLE
Sidebar control header height does not match Tab control height

### ISSUE THREAD

**Issue by Agent47DarkSoul** [equinusocio/material-theme-appbar#3]
The sidebar control's height is more than the tab control height, as you can see from the image below. I tried playing with different sidebar heading assets (small, small@2x, heading@2x). When these asset images are used, the sidebar looks a bit skewed. I am new to Sublime Themes, so I have no idea how to increase the tab control height. Any help would be appreciated.

<img width="1539" alt="screen shot 2016-01-08 at 12 24 14 pm" src="https://cloud.githubusercontent.com/assets/394239/12192516/28017ac8-b605-11e5-90ae-b1d012f0df14.png">

@equinusocio Thanks for your work. I :heart: Material Theme.

**Comment by equinusocio** [comment]
you have to update materiale theme to 2.0.1 before using app bar addon

**Comment by Agent47DarkSoul** [comment]
Works great after upgrading Material Theme to 2.0.1. Thanks :+1:
