### ISSUE TITLE
What's the cog for?

### ISSUE THREAD

**Issue by katerlouis** [equinusocio/material-theme-appbar#32]
It's not working for me. The cog icon besides the "PROJECT" doesn't do anything.
Shouldn't it be doing something? Otherwise I don't see the point of the appbar– there must be something I miss. 

Enlighten me, friends! :)

(Is it possible to remove the shadow between the two parts?)
(And how can one change the project name?)

Thanks guys :)

**Comment by equinusocio** [comment]
This addon is module of the Material Theme, and is pure design, not a functionality. The project label is a static image (I will replace the cog icon). At the moment you can't remove the shadow.

**Comment by katerlouis** [comment]
Okay, then we form this into a feature request! :D
It would be so awesome if the "PROJECT" would actually display the Project title from the sublime-project settings, if given. I often work on multiple projects. When OS X fu**s up the fullscreen order I get confused quite a lot and caught myself coding in the wrong project..
