### ISSUE TITLE
Display project title + "Remove shadow option"

### ISSUE THREAD

**Issue by katerlouis** [equinusocio/material-theme-appbar#33]
<b>Feature Request: Sorry, I somewhy can't set the label to "feature request" – But it is!</b>

Okay, then we form my wish into a feature request! :D

It would be so awesome if the "PROJECT" would actually display the Project title from the sublime-project settings, if given. I often work on multiple projects. When OS X fu**s up the fullscreen order I get confused quite a lot and caught myself coding in the wrong project..

Also an option to remove the shadow would be great.

(I know this would belong in the issues section of the main theme, but it fit's here too and I don't want to spam more)
Is there a way to visually hide the Sidebar Headlines WITHOUT the appbar? I mean hiding so there is extra space, just like in the app bar now. Because so far the appbar has no more use to me than the hidden headlines.

**Comment by equinusocio** [comment]
For a dynamic heading see #5 and #21.

I will search a way to remove the sidebar heading through settings and the PROJECT label will become "EXPLORER"

**Comment by katerlouis** [comment]
Are there "groups" or "job-requests" in github? Where we can find a badass-python-dev?
This feature would be awesome!

**Comment by equinusocio** [comment]
There is a room on Gitter, check the readme 👍 Maybe is a good place to start finding some dev-man

**Comment by oivva** [comment]
> Are there "groups" or "job-requests" in github? Where we can find a badass-python-dev?
This feature would be awesome!

Currently there is no API for that, so enjoy the `Explorer` title. This is better than nothing :wink:
