### ISSUE TITLE
Breaks layout of Sublime Text

### ISSUE THREAD

**Issue by elliottmangham** [equinusocio/material-theme-appbar#34]
Hi, for some reason when I add the appbar it breaks my sublime (see screenshot). 

![screen shot 2016-06-13 at 14 07 20](https://cloud.githubusercontent.com/assets/12933804/16008499/2a945fee-3170-11e6-8f6c-ac9dfcd5c72f.png)

Thanks in advance... Love the material theme!

**Comment by equinusocio** [comment]
Try to purge both themes and reinstall it

**Comment by codepushr** [comment]
Removing both and reinstalling didn't work for me, any other advice?

**Comment by obeewan** [comment]
Maybe a tad late to the party but; I had this issue. I changed to a standard theme, removed the package(s) and emptied the settings of material-theme settings. Reloaded Sublime, then everything back again and it worked.
