### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Lukeout** [equinusocio/material-theme-appbar#36]
I've tried installing it so many times what is my problem here ...

{
	"ignored_packages":
	[
		"Vintage"
	],
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"font_size": 12,
	"material_theme_tree_headings": true, // Show sidebar headings
	"theme": "Material-Theme.sublime-theme",
	"material_theme_tree_headings": true, // Show sidebar headings
	"material_theme_appbar_lime": true,

}

**Comment by equinusocio** [comment]
wut?
