### ISSUE TITLE
Monokai Bright Theme

### ISSUE THREAD

**Issue by giovannipds** [equinusocio/material-theme-appbar#37]
Hello! I would like to request Monokoi Bright Theme version for this theme. I know I can still uses Monokai Bright, in the code part, but that just seems ugly. Or even better, some integrated support of all the others themes to this one, I really don't know if that's possible somehow. =P Cheers and congratulations for this awesome theme and work!

**Comment by equinusocio** [comment]
Try Materialize Package. Is a porting of this theme that use other color schemes, but You will not get the updates from the original material theme package

**Comment by giovannipds** [comment]
@equinusocio thanks for the reply. Cool, I'll try that.

Why do you guys just don't mix up the projects? I mean, both projects have more or less the same purposes, I don't understand why it should have two different projects for almost the same thing. Just a comment, ok? No offenses. But it's something you guys should think about it...

Anyways, congratulations on the theme. =P
