### ISSUE TITLE
Project-Specific Appbar Color?

### ISSUE THREAD

**Issue by KyleKing** [equinusocio/material-theme-appbar#38]
It would be awesome that when I switch projects, my appbar color changes. Is there something that already exists or is there a way to have project-specific colors for material-theme-appbar?

**Comment by thecodechef** [comment]
Yeah this would be nice to have plz make it happen @equinusocio thanks for suggesting this @KyleKing

**Comment by equinusocio** [comment]
Atm it's impossible. Sublime Text allow to overwrite only the basics user settings inside the project file, but not the custom one. More info here:

https://www.sublimetext.com/docs/3/projects.html
