### ISSUE TITLE
Appbar not displaying as expected

### ISSUE THREAD

**Issue by heyrm** [equinusocio/material-theme-appbar#39]
The same issue as [this](https://github.com/equinusocio/material-theme-appbar/issues/2) is happening again.

It does not show anything when installed through Package Control or downloading it from github.

and yes I have added 

```
"material_theme_tree_headings": true, // Show sidebar headings
"material_theme_appbar_lime": true
```

to my settings file.

Sublime Text Build 3114

Any ideas what I am doing wrong?

**Comment by alphapilgrim** [comment]
I as well have this issue.

**Comment by liuzxc** [comment]
I have same issue for Sublime Text Build 3124.

**Comment by liuzxc** [comment]
solved by [material-theme readme](https://github.com/equinusocio/material-theme)

**Comment by equinusocio** [comment]
@liuzxc how?

**Comment by liuzxc** [comment]
@equinusocio you should activate the theme manually.

`Preferences > Packages Settings and choose Material Theme > Activate Material Theme`

**Comment by equinusocio** [comment]
@heyrm

**Comment by heyrm** [comment]
is this working for you @equinusocio ? can you (or @liuzxc) copy and paste me your Preferences.sublime-settings file please?

When I tried it broke my sublime

**Comment by equinusocio** [comment]
Just download the package and run Material Theme Activator

**Comment by heyrm** [comment]
Hey, I have tried this @equinusocio but it seems to break sublime (even after a restart).

also tried on a fresh computer my folders become none-visible and not clickable. 

[![Screen Shot 2016-09-27 at 17.09.58.png](https://s21.postimg.org/fk5q1qglz/Screen_Shot_2016_09_27_at_17_09_58.png)](https://postimg.org/image/cdb6i3w5v/)

**Comment by equinusocio** [comment]
You're not using material theme..
