### ISSUE TITLE
Issue Appbar can't appear if you install it via Package control

### ISSUE THREAD

**Issue by Droyk** [equinusocio/material-theme-appbar#4]
Material Theme - Appbar can't appear if you install it via Package control but appears if you manually install it 
fixed it by manually installing 

my only request is fix this issue if we install Material Theme - Appbar via package control this happens ![](https://cloud.githubusercontent.com/assets/4065569/12187363/7b29b23a-b568-11e5-97ca-765fd0d4c1d9.png)

But if we install this manually via github link https://github.com/equinusocio/material-theme-appbar/releases/tag/v1.0.0 it fix automatically. so plz fix this issue

**Comment by equinusocio** [comment]
Same as #2
