### ISSUE TITLE
Sidebar "folder" black, < > buttons not working

### ISSUE THREAD

**Issue by obeewan** [equinusocio/material-theme-appbar#40]
![image](https://cloud.githubusercontent.com/assets/193725/19040110/08a62a8c-8983-11e6-9d94-d3e92384cad6.png)

- Sublime Text:   3126
- Platform:   windows
- Arch:   x64
- Theme:   3.2.0
- Install via PC:   True
- Dependencies:
    * mdpopups:   1.10.0
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8

**Comment by obeewan** [comment]
Also, settings used:

`"material_theme_compact_sidebar": true,`
`"material_theme_disable_fileicons": true,`
`"material_theme_disable_folder_animation": true,`
`"material_theme_tabs_autowidth": true,`
`"material_theme_tree_headings": true,`

**Comment by equinusocio** [comment]
Same as #991
