### ISSUE TITLE
Material Theme Sidebar header broken

### ISSUE THREAD

**Issue by bedatse** [equinusocio/material-theme-appbar#41]
After the update today we have found that the header over sidebar has been broken.

<img width="688" alt="screen shot 2016-10-04 at 8 36 44 pm" src="https://cloud.githubusercontent.com/assets/7496207/19074342/4b39ff00-8a72-11e6-9175-0690d5c5ac3a.png">

**Comment by bedatse** [comment]
Settings
```
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"theme": "Material-Theme-Darker.sublime-theme",
	"material_theme_compact_sidebar": true,
	"material_theme_disable_folder_animation": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"material_theme_tabs_autowidth": true,
	"material_theme_tabs_separator": true,
	"material_theme_tree_headings": true,
```

**Comment by equinusocio** [comment]
Same as https://github.com/equinusocio/material-theme/issues/991

**Comment by bedatse** [comment]
@equinusocio Thanks for the quick fix and sorry for the duplicate
