### ISSUE TITLE
Missing 'project' in top left

### ISSUE THREAD

**Issue by Rylon** [equinusocio/material-theme-appbar#42]
Hi,

I noticed today that the 'PROJECT' text in the top left is missing since I updated to the latest Sublime Text 3 and Material Theme 3.2.2 - there's just a black box instead.

<img width="469" alt="screen shot 2016-10-04 at 22 08 28" src="https://cloud.githubusercontent.com/assets/438452/19092607/5b452f20-8a7f-11e6-977c-991c0f522668.png">

I'm not sure if this is an issue with Material Theme or the App Bar, but here's some information about my setup:

<img width="532" alt="screen shot 2016-10-04 at 22 10 01" src="https://cloud.githubusercontent.com/assets/438452/19092639/7abeade0-8a7f-11e6-8746-76bafc9b497a.png">

Also it might be worth noting I'm using a Retina display?

Thanks for your help!

**Comment by danechitoaie** [comment]
I think it's same issue as here https://github.com/equinusocio/material-theme/issues/992

1.2.6 just fixed it for me.

Please update and try again.

**Comment by Rylon** [comment]
Thanks @danechitoaie I should've checked that project before I reported here :D Fixed!
