### ISSUE TITLE
Request : Per Project Settings

### ISSUE THREAD

**Issue by MrWaz** [equinusocio/material-theme-appbar#44]
I frequently have two instances running at the same time, let's say one on my active development project and another one to take notes.

To quickly identify one instance from another when using alt + tab, I'd love to be able to set a specific appbar color for each one.

I tried to define a different color in my project settings but it seems the settings are not taken into account

```json
{
    "folders":
    [
        {
            "path": "C:\\Work\\MyNotes"
        }
    ],
    "settings":
    {
        "material_theme_appbar_lime": false,
        "material_theme_appbar_orange": false,
        "material_theme_appbar_purple": true,
        "material_theme_appbar_red": false,
        "material_theme_appbar_yellow": false,
        "material_theme_appbar_indigo": false,
        "material_theme_appbar_pink": false,
        "material_theme_appbar_blue": false,
        "material_theme_appbar_cyan": false,
        "material_theme_appbar_charcoal": false
    }
}
```

Would it be possible to allow such customization?

Keep up the good work

All the best

Waz

**Comment by equinusocio** [comment]
Sublime text doesn't read custom theme settings from the `.sublime-project`file so i can't do anything. This behavior is handled by ST and not by this package.

**Comment by MrWaz** [comment]
ok thanks for the reply
