### ISSUE TITLE
Add `.st-file-icons`

### ISSUE THREAD

**Issue by oivva** [equinusocio/material-theme-appbar#45]
Addons should contain it too.

**Comment by equinusocio** [comment]
Ah. Ok.

**Comment by equinusocio** [comment]
My appbar addon works even without this file. The addon doesn't provider any icons so why the should be placed here?

**Comment by oivva** [comment]
I've just found out that `zz File Icons` can override icons provided by the theme if its addon contains `*.sublime-theme` files.

**Comment by equinusocio** [comment]
Ah, so if any user installare only the appbar addon, without material theme,  he won't see any icons, instead of seeing the icons from zz-File-Icons

**Comment by oivva** [comment]
No. If user install the appbar addon without material theme - everything is ok. But when user installs material theme & appbar addon he will see only `zz File Icons` not the theme's ones.

**Comment by oivva** [comment]
This is because when the user have installed addon & the theme we have two `Material *.sublime-theme` files.

**Comment by equinusocio** [comment]
Yes. But if i have only the addon package no icons Will be displayed if i put .zz-icons-file. Right?

**Comment by oivva** [comment]
Ah, I understood you. Right icons will be used in this case. Sublime will search icons in addons folder if it found nothing it will take icons from the theme package.

**Comment by equinusocio** [comment]
Ok, Right. 👍🏻

**Comment by equinusocio** [comment]
https://github.com/equinusocio/material-theme-appbar/commit/726eeaf5d9e0391efb7c8997ded2153d22f82381
