### ISSUE TITLE
How to disable the appbar

### ISSUE THREAD

**Issue by eveouo** [equinusocio/material-theme-appbar#46]
I just want to use material-theme without appbar.
how to disable the appbar part?
Thanks!
It's a great theme☺️

**Comment by equinusocio** [comment]
Just remove the package and reactivate the theme

**Comment by eveouo** [comment]
But it will download reinstall  and reactive automatically after i restart sublime text

**Comment by equinusocio** [comment]
You have to remove the package through `Package Control: Remove package`
