### ISSUE TITLE
Addon settings

### ISSUE THREAD

**Issue by MandarSant** [equinusocio/material-theme-appbar#48]
how to add this options where and how please help

> "material_theme_tree_headings": true, // Show sidebar headings
> "material_theme_appbar_lime": true,
> "material_theme_appbar_orange": true,
> "material_theme_appbar_purple": true,
> "material_theme_appbar_red": true,
> "material_theme_appbar_yellow": true,
> "material_theme_appbar_indigo": true,
> "material_theme_appbar_pink": true,
> "material_theme_appbar_blue": true,
> "material_theme_appbar_cyan": true,
> "material_theme_appbar_charcoal": true

**Comment by equinusocio** [comment]
Inside the Sublime Text preference file.
https://www.sublimetext.com/docs/3/settings.html
