### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by HelikeLong** [equinusocio/material-theme-appbar#5]
Hello,

Isn't it possible to change the 'Project' word to the project name? I would turn it much more useful than only beautiful.

**Comment by equinusocio** [comment]
wut?

**Comment by ctf0** [comment]
its possible but will need some python logic to make the changes dynamicly

**Comment by equinusocio** [comment]
@ctf0 really? i don't know python so i'm open to PR and collaboration

**Comment by ctf0** [comment]
am in the same boat as you but will try something over the wekend :+1:

**Comment by spacedawwwg** [comment]
+1

**Comment by equinusocio** [comment]
@spacedawwwg you're a python programmer?

**Comment by ianisted** [comment]
+1 for this

**Comment by katerlouis** [comment]
+1 indeed!
Let's find ourselves a python-evangelist!
