### ISSUE TITLE
material_theme_tree_headings not working on Windows?

### ISSUE THREAD

**Issue by shawnlan** [equinusocio/material-theme-appbar#50]
Setting it to false doesn't hide the "folder" label on my Windows 10 desktop. On my Mac it works though.

Running on Sublime 3126.

Here is what I found in the console:

Errors parsing theme:
Unknown attribute value

Any idea?

**Comment by equinusocio** [comment]
I think windows version does not have this key attribute. I can't do anything, i'm sorry. I suggest you to change editor because Sublime Text seems abandoned and unsupported. Material Theme is also available for Atom and Visual Studio Code.

**Comment by shawnlan** [comment]
Really? Sublime Text is abandoned? How do you know?

Atom vs VS Code: Which one do you prefer?

**Comment by equinusocio** [comment]
@shawnlan i like the vsc speed and the functionalities. The vsc team is more active and follow the community needs. Next month will be released some new workbench api so i can improve material theme for vsc. At the moment is my default editor. Check also the extensions marketplace.

**Comment by shawnlan** [comment]
Thank you!
