### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by Amparose** [equinusocio/material-theme-appbar#53]
I have two OSX machines that this isn't working on, one is a completely fresh install and this was the 3rd addon. Works fine on my Win machines. Any ideas?

**Comment by neokio** [comment]
On a fresh install of Sublime Text (build 3143) on a new system, I did the following:

1. installed Material Theme
2. installed Material Them Appbar
3. added this to Prefs > Settings > User:

```
    "material_theme_tree_headings": true , // Show sidebar headings

    "overlay_scroll_bars": "enabled",
    "line_padding_top": 1,
    "line_padding_bottom": 1,
    "always_show_minimap_viewport": true,
    "bold_folder_labels": true,
    "indent_guide_options": [ "draw_normal", "draw_active" ],   // Highlight active indent
    "font_options": [ "gray_antialias" ],                       // For retina Mac
```

4. restarted Sublime Text.

The appbar does not appear.
What am I missing?

**Comment by equinusocio** [comment]
this:
> This project is not more under active development. Since Sublime Text is an obsolete software compared to other editors please consider Material Theme for Visual Studio Code.

>This repo will will keep approving fixing PR from contributors, if there is one.

**Comment by neokio** [comment]
I see, apologies for not noticing!
And thanks for all your amazing work on this in the past :)
