### ISSUE TITLE
material_theme_tree_headings has no effect

### ISSUE THREAD

**Issue by AntonTrapp** [equinusocio/material-theme-appbar#6]
Tried the appbar today - looks great, love the magic coloring ;)

However, I can set material_theme_tree_headings to true, false, restart, ... it does nothing, I always have the "PROJECT" on top of the tree and about 2 empty lines, after that the "normal" tree with the file system structure.

**Comment by AntonTrapp** [comment]
Removed all themes (including material), reinstalled only material, getting "separators" - problem: in dark theme the seperators are so dark that you need to turn up the contrast to maximum so you can see them ;) - any way of "more visible" separators?

**Comment by equinusocio** [comment]
`material_theme_tree_headings ` only hide the tree headings not the "PROJECT" header, and i have no issue with this:
![example](https://cloud.githubusercontent.com/assets/10454741/12509876/0cdfe02a-c106-11e5-814d-26f9cc6e0b0b.gif)

**Comment by AntonTrapp** [comment]
Sorry, misunderstood that. Thank you for the answer!

**Comment by joezimjs** [comment]
This does not work for me on Windows. "Folders" is always showing no matter what I set this to.
