### ISSUE TITLE
Appbar issue when using small tabs

### ISSUE THREAD

**Issue by monkeez** [equinusocio/material-theme-appbar#9]
I'm getting an alignment issue with the appbar when I set the tabs to small:

![capture](https://cloud.githubusercontent.com/assets/5214414/12887668/fb06b44c-cec9-11e5-855c-718e2936db96.PNG)

**Comment by equinusocio** [comment]
Same of #3 
What version of material theme are you using....

**Comment by monkeez** [comment]
OK thanks, for some reason my theme didn't update to the latest last time I ran sublime. Working now.
